apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    name: reslut-app-service
    app: voting-app-demo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    name: result-app-pod
    app: voting-app-demo
